# Generated by Django 5.1.5 on 2025-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
