# Generated by Django 5.1.5 on 2025-02-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tourist", "관광지"),
                            ("restaurant", "맛집"),
                            ("cafe", "카페"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("review_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
